options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west4-docker.pkg.dev/braided-voyage-472209-n6/ml-services/auto-labeler:latest', '.']
  dir: 'components/auto-labeler'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west4-docker.pkg.dev/braided-voyage-472209-n6/ml-services/dataset-splitter:latest', '.']
  dir: 'components/dataset-splitter'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west4-docker.pkg.dev/braided-voyage-472209-n6/ml-services/yolo-trainer:latest', '.']
  dir: 'components/yolo-trainer'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west4-docker.pkg.dev/braided-voyage-472209-n6/ml-services/model-evaluator:latest', '.']
  dir: 'components/model-evaluator'

images:
- 'europe-west4-docker.pkg.dev/braided-voyage-472209-n6/ml-services/auto-labeler:latest'
- 'europe-west4-docker.pkg.dev/braided-voyage-472209-n6/ml-services/dataset-splitter:latest'
- 'europe-west4-docker.pkg.dev/braided-voyage-472209-n6/ml-services/yolo-trainer:latest'
- 'europe-west4-docker.pkg.dev/braided-voyage-472209-n6/ml-services/model-evaluator:latest'