options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 'europe-west4-docker.pkg.dev/data-engineering-vm/yannick-wine-repo/data-ingestion:latest', 
    '.'
  ]
  dir: 'components/data-ingestion'

images:
- 'europe-west4-docker.pkg.dev/data-engineering-vm/yannick-wine-repo/data-ingestion:latest'