steps:
# Step 1: Copy the new best model artifact to the fixed production model path
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '${_NEW_MODEL_URI}', 'gs://yannick-wine-models/production_model/model.joblib']

# Step 2: Build and push the Prediction API Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west4-docker.pkg.dev/data-engineering-vm/yannick-wine-repo/prediction-api:latest', '.']
  dir: 'prediction-api'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west4-docker.pkg.dev/data-engineering-vm/yannick-wine-repo/prediction-api:latest']

# Step 3: Deploy the Prediction API to Cloud Run, making it non-public
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: DeployAPI
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'prediction-api'
    - '--image=europe-west4-docker.pkg.dev/data-engineering-vm/yannick-wine-repo/prediction-api:latest'
    - '--region=europe-west4'
    - '--platform=managed'
    - '--no-allow-unauthenticated' # Secure the API
    - '--set-env-vars=MODEL_BUCKET=yannick-wine-models'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: GetApiUrl
  entrypoint: 'bash'
  args: ['-c', "gcloud run services describe prediction-api --platform=managed --region=europe-west4 --format='value(status.url)' > /workspace/api_url.txt"]

# Step 4: Build and push the Prediction UI Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west4-docker.pkg.dev/data-engineering-vm/yannick-wine-repo/prediction-ui:latest', '.']
  dir: 'prediction-ui'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west4-docker.pkg.dev/data-engineering-vm/yannick-wine-repo/prediction-ui:latest']

# Step 5: Deploy the Prediction UI to Cloud Run, making it public
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    API_URL=$(cat /workspace/api_url.txt)
    gcloud run deploy prediction-ui \
      --image=europe-west4-docker.pkg.dev/data-engineering-vm/yannick-wine-repo/prediction-ui:latest \
      --region=europe-west4 \
      --platform=managed \
      --allow-unauthenticated \
      --set-env-vars=PREDICTOR_API_URL=$$API_URL
