steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '${_NEW_MODEL_URI}', './prediction-api/best.pt']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/data-engineering-vm/ml-services/prediction-api:latest', '.']
  dir: 'prediction-api'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/data-engineering-vm/ml-services/prediction-api:latest']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: DeployAPI
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'prediction-api'
    - '--image=us-central1-docker.pkg.dev/data-engineering-vm/ml-services/prediction-api:latest'
    - '--region=us-central1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--set-env-vars=MODEL_BUCKET=glasses-model'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: GetApiUrl
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud run services describe prediction-api --platform=managed --region=us-central1 --format='value(status.url)' > /workspace/api_url.txt
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/data-engineering-vm/ml-services/prediction-ui:latest', '.']
  dir: 'prediction-ui'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/data-engineering-vm/ml-services/prediction-ui:latest']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    API_URL=$(cat /workspace/api_url.txt)
    gcloud run deploy prediction-ui \
      --image=us-central1-docker.pkg.dev/data-engineering-vm/ml-services/prediction-ui:latest \
      --region=us-central1 \
      --platform=managed \
      --allow-unauthenticated \
      --set-env-vars=PREDICTOR_API_URL=$$API_URL
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '${_NEW_MODEL_URI}', 'gs://glasses-model/production_model/best.pt']

images:
- 'us-central1-docker.pkg.dev/data-engineering-vm/ml-services/prediction-api:latest'
- 'us-central1-docker.pkg.dev/data-engineering-vm/ml-services/prediction-ui:latest'