options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: "python:3.9-slim"
    id: "RunFrontendTests"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pip install pytest flask pandas scikit-learn joblib numpy requests --break-system-packages
        echo "Running frontend unit tests..."
        pytest unit-tests/ -v -p no:warnings --tb=short
    waitFor: ["-"]
  - name: "gcr.io/cloud-builders/docker"
    id: "BuildPredictionAPI"
    args: ["build", "-t", "europe-west4-docker.pkg.dev/data-engineering-vm/yannick-wine-repo/prediction-api:latest", "."]
    dir: "prediction-api"
    waitFor: ["RunFrontendTests"]
  - name: "gcr.io/cloud-builders/docker"
    id: "BuildPredictionUI"
    args: ["build", "-t", "europe-west4-docker.pkg.dev/data-engineering-vm/yannick-wine-repo/prediction-ui:latest", "."]
    dir: "prediction-ui"
    waitFor: ["RunFrontendTests"]
  - name: "gcr.io/cloud-builders/docker"
    id: "PushImages"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker push europe-west4-docker.pkg.dev/data-engineering-vm/yannick-wine-repo/prediction-api:latest
        docker push europe-west4-docker.pkg.dev/data-engineering-vm/yannick-wine-repo/prediction-ui:latest
    waitFor: ["BuildPredictionAPI", "BuildPredictionUI"]
  - name: "gcr.io/cloud-builders/gcloud"
    id: "DeployPredictionAPI"
    args:
      - "run"
      - "deploy"
      - "prediction-api"
      - "--image=europe-west4-docker.pkg.dev/data-engineering-vm/yannick-wine-repo/prediction-api:latest"
      - "--region=europe-west4"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--set-env-vars=CONFIG_BUCKET=yannick-pipeline-root,CONFIG_BLOB=config/model-config.json"
      - "--memory=2Gi"
      - "--cpu=2"
      - "--timeout=120"
    waitFor: ["PushImages"]
  - name: "gcr.io/cloud-builders/gcloud"
    id: "DeployPredictionUI"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        API_URL=$$(gcloud run services describe prediction-api --region=europe-west4 --format='value(status.url)')
        echo "Prediction API URL: $$API_URL"
        gcloud run deploy prediction-ui \
          --image=europe-west4-docker.pkg.dev/data-engineering-vm/yannick-wine-repo/prediction-ui:latest \
          --region=europe-west4 \
          --platform=managed \
          --allow-unauthenticated \
          --set-env-vars=PREDICTOR_API_URL=$$API_URL \
          --memory=512Mi \
          --timeout=60
    waitFor: ["DeployPredictionAPI"]
images:
  - "europe-west4-docker.pkg.dev/data-engineering-vm/yannick-wine-repo/prediction-api:latest"
  - "europe-west4-docker.pkg.dev/data-engineering-vm/yannick-wine-repo/prediction-ui:latest"